app_main:
    path: /
    controller: App\Controller\ReviewStatsHomeController::home

app_view_developer:
    path: /developer/{login}
    controller: App\Controller\ReviewStatsHomeController::viewDeveloper

app_view_prs_waiting_stats:
    path: /prs_waiting_stats
    controller: App\Controller\PRsWaitingStatsController::viewStats

app_view_prs_waiting_review_status:
    path: /prs_waiting_review_status
    controller: App\Controller\PRWaitingReviewStatusController::viewListing

app_receive_github_webhook:
    path: /github_webhook
    controller: App\Controller\ReceiveGitHubWebHookController::receive
