app_main:
    path: /
    controller: App\Controller\ReviewStatsHomeController::home

app_view_developer:
    path: /developer/{login}
    controller: App\Controller\ReviewStatsHomeController::viewDeveloper
