parameters:

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\Controller\ReviewStatsHomeController:
    arguments:
      - '@App\Helper\ReviewStatsService'

  App\Controller\PRsWaitingStatsController:
    arguments:
      - '@App\Helper\PRsWaitingStatsService'

  App\Controller\PRWaitingReviewStatusController:
    arguments:
      - '@App\Helper\PRWaitingReviewStatusListingService'

  App\Controller\ReceiveGitHubWebHookController:

  App\Command\RecordReviewsCommand:
    arguments:
      - '@App\Helper\ReviewRecordService'

  App\Command\RecordPRsWaitingTotalCommand:
    arguments:
      - '@App\Helper\PRsWaitingRecordService'

  App\Command\RecordPRsStatusesCommand:
    arguments:
      - '@App\Helper\PRWaitingReviewStatusRecordService'
      - '@App\Helper\PRWaitingReviewStatusDeleteService'

  App\Database\MySQLPDOProvider:
    arguments:
      - '%env(resolve:APP_DB_HOST)%'
      - '%env(resolve:APP_DB_TABLE)%'
      - '%env(resolve:APP_DB_USER)%'
      - '%env(resolve:APP_DB_PASSWORD)%'

  App\Helper\ReviewStatsService:
    arguments:
      - '@PDO'

  App\Helper\PRsWaitingStatsService:
    arguments:
      - '@PDO'

  App\Helper\PRWaitingReviewStatusListingService:
    arguments:
      - '@PDO'

  App\Helper\PRWaitingReviewStatusDeleteService:
    arguments:
      - '@PDO'

  App\Helper\ReviewRecordService:
    arguments:
      - '%env(resolve:APP_GH_TOKEN)%'
      - '@doctrine.orm.default_entity_manager'

  App\Helper\PRsWaitingRecordService:
    arguments:
      - '%env(resolve:APP_GH_TOKEN)%'
      - '@doctrine.orm.default_entity_manager'

  App\Helper\PRWaitingReviewStatusRecordService:
    arguments:
      - '%env(resolve:APP_GH_TOKEN)%'
      - '@doctrine.orm.default_entity_manager'

  PDO:
    class: PDO
    factory: [ '@App\Database\MySQLPDOProvider', 'getPDO' ]

  App\Database\DataFixtures\ReviewStatsFixtures:
    tags:
      - 'doctrine.fixture.orm'

  App\Database\DataFixtures\PRWaitingStatsFixtures:
    tags:
      - 'doctrine.fixture.orm'
