parameters:

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\Controller\MainController:
    arguments:
      - '@App\Helper\StatsService'

  App\Command\RecordReviewsCommand:
    arguments:
      - '@App\Helper\RecordService'

  App\Database\MySQLPDOProvider:
    arguments:
      - '%env(resolve:APP_DB_HOST)%'
      - '%env(resolve:APP_DB_TABLE)%'
      - '%env(resolve:APP_DB_USER)%'
      - '%env(resolve:APP_DB_PASSWORD)%'

  App\Helper\StatsService:
    arguments:
      - '@PDO'

  App\Helper\RecordService:
    arguments:
      - '%env(resolve:APP_GH_TOKEN)%'
      - '@doctrine.orm.default_entity_manager'

  PDO:
    class: PDO
    factory: [ '@App\Database\MySQLPDOProvider', 'getPDO' ]

  App\Database\DataFixtures\ReviewStatsFixtures:
    tags:
      - 'doctrine.fixture.orm'
